# This is a basic workflow to help you get started with Actions

name: CI - Diff To Ancestor

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
 #   branches: [ main ]

jobs:
  my-job:
    name: Diff
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Run commands
        uses: matlab-actions/run-command@v1
        with:
          command: diffGitHub
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: C:\actions-runner\_work\Airframe-Project-GitHub-Actions\Airframe-Project-GitHub-Actions\*.pdf
