
name: PullRequest - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [ main ]

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
 #     - name: Step that prints name of pull request's base branch
 #       run: |
 #        echo "Pull request's head branch is: ${HEAD_BRANCH}"
 #         env:
 #          HEAD_BRANCH: ${{ github.head_ref }} 
 #          if: github.event_name == 'pull_request'
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
        with:
          command: diffGitHub_pullrequest(github.head_ref)
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: C:\actions-runner\_work\Airframe-Project-GitHub-Actions\Airframe-Project-GitHub-Actions\*.html
