
name: PushToMain - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run test oturum
on:
  # Triggers the workflow on push events but only for the main branch
 
 push:
    branches: [ main ]

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v1

#   Copyright 2022 The MathWorks, Inc.
