name: Run Default Tasks in Build File
on: [push]
jobs:
  my-job:
    name: Run MATLAB Build
    runs-on: ubuntu-latest

    strategy:
        matrix:
           release: [R2021b, R2022b,R2023b]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: ${{ github.workspace }}\*.html
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v1
        with:
          command: runtests